services:
  nginx:
    image: "nginx:latest"
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000" # Grafana
    volumes:
      - /var/nginx-proxy/configs:/etc/nginx/conf.d
      - /var/nginx-proxy/static:/var/www/static
      - ./certs:/etc/letsencrypt
      - ./scripts/docker:/app/scripts
    env_file:
      - ".env_dev"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "50m"
    networks:
      - default
