server {
    listen 80 default_server;

    location = /nginx-proxy/version/ {
        default_type text/plain;
        return 200 "v1.0.0";
    }

    location / {
        return 404 "no project has registered this domain with nginx-proxy yet\n";
    }
}

# Dev-only fallback to TLS handshake + 404 instead of a connection error.
server {
    listen 443 ssl default_server;
    ssl_certificate     /etc/letsencrypt/live/_default/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/_default/privkey.pem;

    return 404 "no project has registered this domain with nginx-proxy yet\n";
}
